### ISSUE TITLE
question...

### ISSUE THREAD

**Issue by griskiiy** [XrDev123/prysmax-stealer-logger#1]
where can i download it from? or is it license only? and i want to buy the license i need contact..

**Comment by XrDev123** [comment]
you can download all files from here and the builders there
![image](https://github.com/user-attachments/assets/579799ee-d480-40db-ad74-1cb9d607cc8c)

about the license you can contact me on discord. my alts username is below
![image](https://github.com/user-attachments/assets/3df81a15-a055-4d54-bd07-ff69004d4ef6)
